Added Yandex
openSUSE/search-o-o pull request #32
Opened 2022-04-17 11:49 UTC by JignasP

Yandex search had been added

2022-04-17 12:36 UTC, hellcp requested changes

2022-04-17 12:36 UTC, hellcp commented on _data/search-engines.yml
> -# Removed Givero Search as it is discontinued
I would keep that note

2022-04-17 12:36 UTC, hellcp commented on assets/search/Yandex.svg
> +<!-- Created with Inkscape (http://www.inkscape.org/) -->
Would you export the svg as optimized svg in inkscape?

2022-04-17 12:36 UTC, hellcp commented on assets/search/Yandex.svg
> +   width="50mm"
I would rather have the svg the same size as the others in this directory

2022-04-18 02:50 UTC, JignasP commented
Surely I will make the changes.

2022-04-20 07:47 UTC, closed without merging